sdk: "/Users/mva/projects/rhomobile/rhodes"
sdkversion: 5.8.0
name: kitchensinkRuby
version: 1.0
vendor: rhomobile
build: debug
applog: rholog.txt
app_type: "rhoelements"
iphone:
  configuration: Release
  sdk: iphonesimulator10.2
  #provisionprofile:
  #codesignidentity:
  #entitlements:
  BundleIdentifier: com.tau-technologies.kitchensinkruby
  BundleURLScheme: kitchensinkruby
  production:
    ipa_itunesartwork_image: "./production/iTunesArtwork.png"
  # Note: Specifies the URL schemes the app is able to call using Rho.System.runApplication
  #ApplicationQueriesSchemes: ["scheme1", "scheme2"]
wp8:
  productid: '1ef3a390-a41a-0134-eff9-60f81db5e3c0'
uwp:
  productid: 'caa0300f-1021-40aa-bb98-27c5547616fa'
  target: 'ARM'
android:
  #manifest_template: 'AndroidManifest.erb'
  version: 4.1.0
  # Note: in order to simplify debugging only app messages and system channels with priority informative and higher, and any errors are enabled by default
  logcatFilter: APP:I StrictMode:I DEBUG:I *:E

wm:
  #sdk: "MC3000c50b (ARMV4I)"
  #sdk: "Windows Mobile 6.5.3 Professional DTK (ARMV4I)"
  extensions:
    - webkit

win32:
  msvc: 2015
  deployqt: 1
  deploymsvc: 1

extensions:
 - mediacapture
 - barcode
 - indicators
 - hardwarekeys
# - signature

rhobundle:
  exclude_items:
  - thumb.db
