#sdk: "../rhodes"
sdkversion: 7.1.0
name: KitchensinkRuby
version: 1.0.7
vendor: rhomobile
build: release #debug
applog: rholog.txt
iphone:
  configuration: Release
  sdk: iphonesimulator10.3
  #provisionprofile:
  #codesignidentity:
  #entitlements:
  BundleIdentifier: com.tau-technologies.kitchensinkruby
  BundleURLScheme: kitchensinkruby
  production:
    ipa_itunesartwork_image: "./production/iTunesArtwork.png"
  # Note: Specifies the URL schemes the app is able to call using Rho.System.runApplication
  #ApplicationQueriesSchemes: ["scheme1", "scheme2"]
  extensions: ["hardwarekeys", "barcode", "screenorientation", "indicators", "sensor", "signature", "audiocapture", "mediacapture","printing", "mediaplayer", "printing_zebra"]
wp8:
  productid: '98cef7b0-88bb-0134-7b78-60f81db5e3c0'
uwp:
  productid: 'caa0300f-1021-40aa-bb98-27c5547616fa'
  target: 'ARM'
  extensions: ["sensor", "mediacapture"]
android:
  #manifest_template: 'AndroidManifest.erb'
  #version: 9
  minSDK: 23
  targetSDK: 29
  # Note: in order to simplify debugging only app messages and system channels with priority informative and higher, and any errors are enabled by default
  logcatFilter: APP:I StrictMode:I DEBUG:I *:E
  extensions:
  - hardwarekeys
  - barcode
  - screenorientation
  - indicators
  - sensor
  - websocket
  - signature
  - audiocapture
  - mediacapture
  - printing
  - mediaplayer
  - printing_zebra
  - openssl
  - openssl.so
  - digest
  - digest-sha1
  - digest-sha2
  - digest-md5
  - ezcrypto

  abis:
  - arm
  - x86
  - aarch64
linux:

wm:
  #sdk: "MC3000c50b (ARMV4I)"
  #sdk: "Windows Mobile 6.5.3 Professional DTK (ARMV4I)"
  extensions: ["webkit", "barcode", "screenorientation", "cardreader", "indicators", "sensor", "audiocapture", "mediacapture"]

win32:
  msvc: 2015
  deployqt: 1
  deploymsvc: 1
  #extensions: ["barcode", "mediacapture"]

extensions:
# - mediacapture
# - barcode
# - indicators
# - hardwarekeys
# - signature

rhobundle:
  exclude_items:
  - thumb.db
